name: Resolve Issue with OpenHands

on:
  issues:
    types: [labeled]
  pull_request:
    types: [assigned]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  call-openhands-resolver:
    runs-on: ubuntu-latest

    steps:
      - name: AWS CLI install
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: AWS set Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Wait until cache.txt is removed from S3
        run: |
          while aws s3 ls s3://github-open-hands/cache.txt | grep cache.txt; do
            echo "cache.txt exists. Sleeping for 60 seconds."
            sleep 60
          done
          echo "cache.txt does not exist. Continuing."

      - name: Generate cache.txt with project name and current time
        run: |
          echo "Project: open-hands-demo" > cache.txt
          echo "Time: $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> cache.txt

      - name: Upload file to S3
        run: aws s3 cp ./cache.txt s3://github-open-hands/ --quiet

      - name: call-openhands-resolver
        if: |
          (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'fix-me') ||
          (github.event_name == 'pull_request' && github.event.action == 'assigned') ||
          (github.event_name == 'issue_comment' && contains(github.event.comment.body, vars.OPENHANDS_MACRO || '@openhands-agent')) ||
          (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, vars.OPENHANDS_MACRO || '@openhands-agent'))
        uses: All-Hands-AI/OpenHands/.github/workflows/openhands-resolver.yml@main
        with:
          macro: ${{ vars.OPENHANDS_MACRO || '@openhands-agent' }}
          max_iterations: ${{ fromJson(vars.OPENHANDS_MAX_ITER || '50') }}
          base_container_image: ${{ vars.OPENHANDS_BASE_CONTAINER_IMAGE || '' }}
          LLM_MODEL: ${{ vars.LLM_MODEL || 'anthropic/claude-sonnet-4-20250514' }}
          target_branch: ${{ vars.TARGET_BRANCH || 'main' }}
          runner: ${{ vars.TARGET_RUNNER }}
        # secrets:
          # PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          # PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
          # LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          # LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}

      - name: Delete cache.txt from S3
        if: ${{ always() }}
        run: aws s3 rm s3://github-open-hands/cache.txt
