name: s3-cache-demo

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: AWS CLI install
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: AWS set Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Wait until cache.txt is removed from S3
      run: |
        while aws s3 ls s3://github-open-hands/cache.txt | grep cache.txt; do
          echo "cache.txt exists. Sleeping for 60 seconds."
          sleep 60
        done
        echo "cache.txt does not exist. Continuing."

    - name: Generate cache.txt with project name and current time
      run: |
        echo "Project: open-hands-demo" > cache.txt
        echo "Time: $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> cache.txt
    
    - name: Upload file to S3
      run: aws s3 cp ./cache.txt s3://github-open-hands/ --quiet

    - name: Wait for 60 seconds
      run: sleep 60
    
    - name: Delete cache.txt from S3
      run: aws s3 rm s3://github-open-hands/cache.txt
