name: s3-cache-demo

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: AWS CLI install
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: AWS set Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Generate cache.txt with project name and current time
      run: |
        echo "Project: open-hands-demo" > cache.txt
        echo "Time: $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> cache.txt
    
    - name: Upload cache.txt to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read
        bucket: github-open-hands
        endpoint-url: https://s3.amazonaws.com
        source_dir: .
        dest_dir: .
        files: cache.txt
      env:
        AWS_S3_BUCKET: github-open-hands
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-1
